// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    /// <summary>
    /// <para>syntax = "proto3";</para>
    /// <para>option java_outer_classname = "LivePB";</para>
    /// <para> 12001</para>
    /// <para>获取地图</para>
    /// </summary>
    public partial class CSGetMiGongMap
    {
    }

    public partial class SCGetMiGongMap
    {
        public List<int> Map { get; set; }

    }

    /// <summary> 返回行走路线</summary>
    public partial class CSSendWalkingRoute
    {
        public List<int> Route { get; set; }

    }

    public partial class SCSendWalkingRoute
    {
    }

    /// <summary> 通用协议</summary>
    public partial class CSCommon
    {
        public List<string> Route { get; set; }

    }

    public partial class SCCommon
    {
        public List<string> Route { get; set; }

    }

}
