// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/MiGongPB.proto

package com.protocol;

public final class MiGongPB {
  private MiGongPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CSGetMiGongMapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code CSGetMiGongMap}
   *
   * <pre>
   *option java_outer_classname = "LivePB";
   * 12001
   *------------------------------------------------------房间外的
   * </pre>
   */
  public static final class CSGetMiGongMap extends
      com.google.protobuf.GeneratedMessage
      implements CSGetMiGongMapOrBuilder {
    // Use CSGetMiGongMap.newBuilder() to construct.
    private CSGetMiGongMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSGetMiGongMap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSGetMiGongMap defaultInstance;
    public static CSGetMiGongMap getDefaultInstance() {
      return defaultInstance;
    }

    public CSGetMiGongMap getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSGetMiGongMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protocol.MiGongPB.internal_static_CSGetMiGongMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protocol.MiGongPB.internal_static_CSGetMiGongMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protocol.MiGongPB.CSGetMiGongMap.class, com.protocol.MiGongPB.CSGetMiGongMap.Builder.class);
    }

    public static com.google.protobuf.Parser<CSGetMiGongMap> PARSER =
        new com.google.protobuf.AbstractParser<CSGetMiGongMap>() {
      public CSGetMiGongMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSGetMiGongMap(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSGetMiGongMap> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protocol.MiGongPB.CSGetMiGongMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protocol.MiGongPB.CSGetMiGongMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CSGetMiGongMap}
     *
     * <pre>
     *option java_outer_classname = "LivePB";
     * 12001
     *------------------------------------------------------房间外的
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protocol.MiGongPB.CSGetMiGongMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protocol.MiGongPB.internal_static_CSGetMiGongMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protocol.MiGongPB.internal_static_CSGetMiGongMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protocol.MiGongPB.CSGetMiGongMap.class, com.protocol.MiGongPB.CSGetMiGongMap.Builder.class);
      }

      // Construct using com.protocol.MiGongPB.CSGetMiGongMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protocol.MiGongPB.internal_static_CSGetMiGongMap_descriptor;
      }

      public com.protocol.MiGongPB.CSGetMiGongMap getDefaultInstanceForType() {
        return com.protocol.MiGongPB.CSGetMiGongMap.getDefaultInstance();
      }

      public com.protocol.MiGongPB.CSGetMiGongMap build() {
        com.protocol.MiGongPB.CSGetMiGongMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protocol.MiGongPB.CSGetMiGongMap buildPartial() {
        com.protocol.MiGongPB.CSGetMiGongMap result = new com.protocol.MiGongPB.CSGetMiGongMap(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protocol.MiGongPB.CSGetMiGongMap) {
          return mergeFrom((com.protocol.MiGongPB.CSGetMiGongMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protocol.MiGongPB.CSGetMiGongMap other) {
        if (other == com.protocol.MiGongPB.CSGetMiGongMap.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protocol.MiGongPB.CSGetMiGongMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protocol.MiGongPB.CSGetMiGongMap) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CSGetMiGongMap)
    }

    static {
      defaultInstance = new CSGetMiGongMap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CSGetMiGongMap)
  }

  public interface SCGetMiGongMapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 map = 1;
    /**
     * <code>repeated int32 map = 1;</code>
     *
     * <pre>
     * </pre>
     */
    java.util.List<java.lang.Integer> getMapList();
    /**
     * <code>repeated int32 map = 1;</code>
     *
     * <pre>
     * </pre>
     */
    int getMapCount();
    /**
     * <code>repeated int32 map = 1;</code>
     *
     * <pre>
     * </pre>
     */
    int getMap(int index);
  }
  /**
   * Protobuf type {@code SCGetMiGongMap}
   */
  public static final class SCGetMiGongMap extends
      com.google.protobuf.GeneratedMessage
      implements SCGetMiGongMapOrBuilder {
    // Use SCGetMiGongMap.newBuilder() to construct.
    private SCGetMiGongMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCGetMiGongMap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCGetMiGongMap defaultInstance;
    public static SCGetMiGongMap getDefaultInstance() {
      return defaultInstance;
    }

    public SCGetMiGongMap getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCGetMiGongMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                map_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              map_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                map_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                map_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          map_ = java.util.Collections.unmodifiableList(map_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protocol.MiGongPB.internal_static_SCGetMiGongMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protocol.MiGongPB.internal_static_SCGetMiGongMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protocol.MiGongPB.SCGetMiGongMap.class, com.protocol.MiGongPB.SCGetMiGongMap.Builder.class);
    }

    public static com.google.protobuf.Parser<SCGetMiGongMap> PARSER =
        new com.google.protobuf.AbstractParser<SCGetMiGongMap>() {
      public SCGetMiGongMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCGetMiGongMap(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCGetMiGongMap> getParserForType() {
      return PARSER;
    }

    // repeated int32 map = 1;
    public static final int MAP_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> map_;
    /**
     * <code>repeated int32 map = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getMapList() {
      return map_;
    }
    /**
     * <code>repeated int32 map = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public int getMapCount() {
      return map_.size();
    }
    /**
     * <code>repeated int32 map = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public int getMap(int index) {
      return map_.get(index);
    }

    private void initFields() {
      map_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < map_.size(); i++) {
        output.writeInt32(1, map_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < map_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(map_.get(i));
        }
        size += dataSize;
        size += 1 * getMapList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protocol.MiGongPB.SCGetMiGongMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protocol.MiGongPB.SCGetMiGongMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SCGetMiGongMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protocol.MiGongPB.SCGetMiGongMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protocol.MiGongPB.internal_static_SCGetMiGongMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protocol.MiGongPB.internal_static_SCGetMiGongMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protocol.MiGongPB.SCGetMiGongMap.class, com.protocol.MiGongPB.SCGetMiGongMap.Builder.class);
      }

      // Construct using com.protocol.MiGongPB.SCGetMiGongMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        map_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protocol.MiGongPB.internal_static_SCGetMiGongMap_descriptor;
      }

      public com.protocol.MiGongPB.SCGetMiGongMap getDefaultInstanceForType() {
        return com.protocol.MiGongPB.SCGetMiGongMap.getDefaultInstance();
      }

      public com.protocol.MiGongPB.SCGetMiGongMap build() {
        com.protocol.MiGongPB.SCGetMiGongMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protocol.MiGongPB.SCGetMiGongMap buildPartial() {
        com.protocol.MiGongPB.SCGetMiGongMap result = new com.protocol.MiGongPB.SCGetMiGongMap(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          map_ = java.util.Collections.unmodifiableList(map_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.map_ = map_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protocol.MiGongPB.SCGetMiGongMap) {
          return mergeFrom((com.protocol.MiGongPB.SCGetMiGongMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protocol.MiGongPB.SCGetMiGongMap other) {
        if (other == com.protocol.MiGongPB.SCGetMiGongMap.getDefaultInstance()) return this;
        if (!other.map_.isEmpty()) {
          if (map_.isEmpty()) {
            map_ = other.map_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMapIsMutable();
            map_.addAll(other.map_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protocol.MiGongPB.SCGetMiGongMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protocol.MiGongPB.SCGetMiGongMap) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 map = 1;
      private java.util.List<java.lang.Integer> map_ = java.util.Collections.emptyList();
      private void ensureMapIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          map_ = new java.util.ArrayList<java.lang.Integer>(map_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 map = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getMapList() {
        return java.util.Collections.unmodifiableList(map_);
      }
      /**
       * <code>repeated int32 map = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public int getMapCount() {
        return map_.size();
      }
      /**
       * <code>repeated int32 map = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public int getMap(int index) {
        return map_.get(index);
      }
      /**
       * <code>repeated int32 map = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setMap(
          int index, int value) {
        ensureMapIsMutable();
        map_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 map = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addMap(int value) {
        ensureMapIsMutable();
        map_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 map = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addAllMap(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMapIsMutable();
        super.addAll(values, map_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 map = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearMap() {
        map_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SCGetMiGongMap)
    }

    static {
      defaultInstance = new SCGetMiGongMap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SCGetMiGongMap)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CSGetMiGongMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CSGetMiGongMap_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SCGetMiGongMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SCGetMiGongMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025protos/MiGongPB.proto\"\020\n\016CSGetMiGongMa" +
      "p\"\035\n\016SCGetMiGongMap\022\013\n\003map\030\001 \003(\005B\016\n\014com." +
      "protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CSGetMiGongMap_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CSGetMiGongMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CSGetMiGongMap_descriptor,
              new java.lang.String[] { });
          internal_static_SCGetMiGongMap_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SCGetMiGongMap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SCGetMiGongMap_descriptor,
              new java.lang.String[] { "Map", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
