// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    /// <summary>
    /// <para>option java_outer_classname = "AccountPB";</para>
    /// <para>10001</para>
    /// </summary>
    public partial class CSLogin
    {
        public string AccountId { get; set; }

        public string Url { get; set; }

        public string Ip { get; set; }

    }

    public partial class SCLogin
    {
        public string SessionId { get; set; }

    }

    public partial class CSLogout
    {
        public string AccountId { get; set; }

    }

    public partial class SCLogout
    {
    }

}
