// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    /// <summary>
    /// <para>option java_outer_classname = "BasePB";</para>
    /// <para> opcode_start=10101</para>
    /// </summary>
    public partial class SCException
    {
        public int ErrCode { get; set; }

        public int CsOpcode { get; set; }

        /// <summary> 客户端发过来的消息</summary>
        public int ScOpcode { get; set; }

        /// <summary> 服务端发给客户端的消息</summary>
        public string ErrMsg { get; set; }

    }

}
