// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    /// <summary>
    /// <para>syntax = "proto3";</para>
    /// <para>option java_outer_classname = "LivePB";</para>
    /// <para> 12001</para>
    /// <para></para>
    /// <para>推图/////////////////////////////////////</para>
    /// <para> 进入游戏时，获取迷宫的配置，和当前所处于的关卡</para>
    /// </summary>
    public partial class CSBaseInfo
    {
    }

    public partial class SCBaseInfo
    {
        public int Energy { get; set; }

        /// <summary> 玩家精力</summary>
        public List<Example.PBSysPara> SysParas { get; set; }

        /// <summary> 系统参数</summary>
        public List<Example.PBNewGuide> NewGuide { get; set; }

        /// <summary> 新手引导信息</summary>
        public int OpenPass { get; set; }

    }

    public partial class PBNewGuide
    {
        public int Id { get; set; }

        public int Step { get; set; }

    }

    public partial class PBSysPara
    {
        public string Key { get; set; }

        public string Value { get; set; }

    }

    /// <summary> 完成新手引导</summary>
    public partial class CSNewGuideFinish
    {
        public int Id { get; set; }

        public int Step { get; set; }

    }

    public partial class SCNewGuideFinish
    {
    }

    public partial class CSGetMiGongLevel
    {
    }

    public partial class SCGetMiGongLevel
    {
        public List<int> StarInLevel { get; set; }

        /// <summary> 已经过的关卡的星数</summary>
        public int PassCount { get; set; }

    }

    /// <summary> 获取迷宫</summary>
    public partial class CSGetMiGongMap
    {
        public int Pass { get; set; }

    }

    public partial class SCGetMiGongMap
    {
        public int Pass { get; set; }

        public List<int> Map { get; set; }

        public int Time { get; set; }

        /// <summary> 时间</summary>
        public int Speed { get; set; }

        /// <summary> 速度</summary>
        public int Start { get; set; }

        /// <summary> 起点</summary>
        public int End { get; set; }

        /// <summary> 终点</summary>
        public List<Example.PBBeanInfo> Beans { get; set; }

        /// <summary> 豆子</summary>
        public int Star1 { get; set; }

        /// <summary> 一星目标分数</summary>
        public int Star2 { get; set; }

        /// <summary> 二星目标分数</summary>
        public int Star3 { get; set; }

        /// <summary> 三星目标分数</summary>
        public int Star4 { get; set; }

        /// <summary> 四星目标分数</summary>
        public int Energy { get; set; }

        /// <summary> 消耗体力</summary>
        public string Route { get; set; }

    }

    /// <summary> 豆子信息</summary>
    public partial class PBBeanInfo
    {
        public int Pos { get; set; }

        /// <summary> 豆子的位置</summary>
        public int Score { get; set; }

    }

    /// <summary> 成功或失败 :</summary>
    public partial class CSPassFinish
    {
        public int Pass { get; set; }

        public int Success { get; set; }

        public List<int> Route { get; set; }

    }

    public partial class SCPassFinish
    {
        public int OpenLevel { get; set; }

        /// <summary> 已经开启的leve</summary>
        public int OpenPass { get; set; }

        /// <summary> 已经开启的关卡</summary>
        public int Success { get; set; }

    }

    /// <summary> 使用道具</summary>
    public partial class CSUseItem
    {
        public int ItemId { get; set; }

    }

    public partial class SCUseItem
    {
    }

    /// <summary>无尽版///////////////////////////////////////</summary>
    public partial class CSUnlimitedInfo
    {
    }

    public partial class SCUnlimitedInfo
    {
        public List<Example.PBUnlimitedRankInfo> UnlimitedRankInfo { get; set; }

        public int Pass { get; set; }

        /// <summary> 关卡数</summary>
        public int Star { get; set; }

        /// <summary> 无线关卡已经有的星数</summary>
        public int Rank { get; set; }

    }

    public partial class PBUnlimitedRankInfo
    {
        public string UserId { get; set; }

        /// <summary> 玩家id</summary>
        public string UserName { get; set; }

        /// <summary> 玩家名</summary>
        public int Pass { get; set; }

        /// <summary> 关卡数</summary>
        public int Star { get; set; }

        /// <summary> 星数</summary>
        public int Rank { get; set; }

    }

    public partial class CSUnlimitedGo
    {
    }

    public partial class SCUnlimitedGo
    {
        public int Pass { get; set; }

        /// <summary> 关卡数</summary>
        public List<int> Map { get; set; }

        public int Time { get; set; }

        /// <summary> 时间</summary>
        public int Speed { get; set; }

        /// <summary> 速度</summary>
        public int Start { get; set; }

        /// <summary> 起点</summary>
        public int End { get; set; }

        /// <summary> 终点</summary>
        public List<Example.PBBeanInfo> Beans { get; set; }

        /// <summary> 豆子的位置</summary>
        public int Star1 { get; set; }

        /// <summary> 一星目标分数</summary>
        public int Star2 { get; set; }

        /// <summary> 二星目标分数</summary>
        public int Star3 { get; set; }

        /// <summary> 三星目标分数</summary>
        public int Star4 { get; set; }

        /// <summary> 四星目标分数</summary>
        public int Energy { get; set; }

    }

    /// <summary> 成功或失败 :</summary>
    public partial class CSUnlimitedFinish
    {
        public int Pass { get; set; }

        /// <summary> 关卡数</summary>
        public int Success { get; set; }

        public List<int> Route { get; set; }

    }

    public partial class SCUnlimitedFinish
    {
        public int OpenPass { get; set; }

        /// <summary> 已经开启的关卡</summary>
        public int Success { get; set; }

    }

    /// <summary>
    /// <para>联机对战///////////////////////////////////////</para>
    /// <para> 请求匹配（放入匹配队列），匹配完成创建房间并推送，操作（移动，道具），位置同步和校验（全缓存），到达终点请求和同步，结束推送同步，房间心跳</para>
    /// <para> 请求匹配，返回房间及信息，开始游戏，发送操作（移动，道具），接收操作，发送到达终点，接收到达终点，接收游戏结束，房间心跳</para>
    /// <para> 请求匹配 TODO 取消匹配</para>
    /// <para> 获取在线信息</para>
    /// </summary>
    public partial class CSGetOnlineInfo
    {
    }

    public partial class SCGetOnlineInfo
    {
        public int Score { get; set; }

        /// <summary> 天梯积分</summary>
        public string Title { get; set; }

        /// <summary> 称谓</summary>
        public int Rank { get; set; }

        /// <summary> 排名</summary>
        public List<Example.PBOnlineRankInfo> RankInfos { get; set; }

    }

    public partial class PBOnlineRankInfo
    {
        public string UserId { get; set; }

        /// <summary> 玩家账号</summary>
        public string Name { get; set; }

        /// <summary> 玩家名</summary>
        public int Score { get; set; }

        /// <summary> 天梯积分</summary>
        public string Title { get; set; }

        /// <summary> 称谓</summary>
        public int Rank { get; set; }

    }

    /// <summary> 匹配</summary>
    public partial class CSMatching
    {
    }

    public partial class SCMatching
    {
    }

    /// <summary> 取消匹配</summary>
    public partial class CSCancelMatching
    {
    }

    public partial class SCCancelMatching
    {
    }

    /// <summary> 推送，匹配成功：地图，自己的起点，终点。其他人的起点，终点，玩家名，玩家编号</summary>
    public partial class SCMatchingSuccess
    {
        public List<int> Map { get; set; }

        public int Time { get; set; }

        /// <summary> 时间</summary>
        public int Speed { get; set; }

        /// <summary> 速度</summary>
        public int Start { get; set; }

        /// <summary> 起点</summary>
        public int End { get; set; }

        /// <summary> 终点</summary>
        public List<Example.PBOtherInfo> OtherInfos { get; set; }

        /// <summary> 其它玩家信息</summary>
        public List<Example.PBBeanInfo> Beans { get; set; }

    }

    public partial class PBOtherInfo
    {
        public string UserId { get; set; }

        /// <summary> 玩家id</summary>
        public string UserName { get; set; }

        /// <summary> 玩家名</summary>
        public int Start { get; set; }

        /// <summary> 起点</summary>
        public int End { get; set; }

    }

    /// <summary> 推送，匹配失败</summary>
    public partial class SCMatchingFail
    {
    }

    /// <summary> 推送，开始游戏</summary>
    public partial class SCBegin
    {
    }

    /// <summary> 玩家移动操作</summary>
    public partial class CSMove
    {
        public float PosX { get; set; }

        /// <summary> 当前位置</summary>
        public float PosY { get; set; }

        /// <summary> 当前位置</summary>
        public int Dir { get; set; }

        /// <summary> 方向</summary>
        public int Speed { get; set; }

    }

    public partial class SCMove
    {
    }

    /// <summary> 推送移动操作</summary>
    public partial class SCUserMove
    {
        public List<Example.PBUserMoveInfo> UserMoveInfos { get; set; }

    }

    public partial class PBUserMoveInfo
    {
        public string UserId { get; set; }

        /// <summary> 当前位置</summary>
        public float PosX { get; set; }

        /// <summary> 当前位置</summary>
        public float PosY { get; set; }

        /// <summary> 当前位置</summary>
        public int Dir { get; set; }

        /// <summary> 方向</summary>
        public int Speed { get; set; }

        /// <summary> 速度</summary>
        public int Frame { get; set; }

    }

    /// <summary> 玩家吃豆</summary>
    public partial class CSEatBean
    {
        public int BeanPos { get; set; }

    }

    public partial class SCEatBean
    {
    }

    /// <summary> 推送吃豆</summary>
    public partial class SCSendEatBean
    {
        public List<Example.PBEatBeanInfo> Beans { get; set; }

    }

    public partial class PBEatBeanInfo
    {
        public string UserId { get; set; }

        /// <summary> 玩家id</summary>
        public int BeanPos { get; set; }

    }

    /// <summary> 玩家到达终点</summary>
    public partial class CSArrived
    {
        public int Pos { get; set; }

    }

    public partial class SCArrived
    {
    }

    /// <summary> 推送，玩家到达终点</summary>
    public partial class SCUserArrived
    {
        public string UserId { get; set; }

    }

    /// <summary> 推送，游戏结束：排名</summary>
    public partial class SCGameOver
    {
        public int OverType { get; set; }

        /// <summary> 0其它，1都抵达终点，2时间到</summary>
        public List<Example.PBGameOverUserInfo> UserInfos { get; set; }

    }

    public partial class PBGameOverUserInfo
    {
        public string UserId { get; set; }

        /// <summary> 玩家id</summary>
        public string UserName { get; set; }

        /// <summary> 玩家名称</summary>
        public int Rank { get; set; }

        /// <summary> 排名</summary>
        public int Score { get; set; }

        /// <summary> 分数</summary>
        public int Arrived { get; set; }

    }

    /// <summary> 房间心跳包</summary>
    public partial class CSRoomHeart
    {
    }

    public partial class SCRoomHeart
    {
    }

    public partial class CSSendWalkingRoute
    {
        public List<int> Route { get; set; }

    }

    public partial class SCSendWalkingRoute
    {
    }

    public partial class CSCommon
    {
        public List<string> Route { get; set; }

    }

    public partial class SCCommon
    {
        public List<string> Route { get; set; }

    }

}
